spring:
  datasource:
    url: jdbc:h2:mem:employee
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  session:
    jdbc:
      initialize-schema: always
      schema: classpath:database/schema.sql