retry-config:
  initial-interval-ms: 100
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url-alt: http://schema-registry
  schema-registry-url: http://localhost:8081
  topic-name: employee-topic
  topic-names-to-create:
    - employee-topic
  num-of-partitions: 3
  replication-factor: 3